export const PRODUCTS = [
    {id: 1, name: 'Science@Home (1 month)', price: 1500, is_shipping: false},
    {id: 2, name: 'Science@Home (3 months)', price: 3300, is_shipping: false},
    {id: 3, name: 'Online Classes (1 week)', price: 600, is_shipping: false},
    {id: 4, name: 'Pro Athlete Nutrition Program', price: 700, is_shipping: false},
    {id: 5, name: 'General Nutrition Program', price: 600, is_shipping: false},
    {id: 6, name: '1 Class', price: 100, is_shipping: false},
    {id: 8, name: 'Online Superheroes Program (12 sessions)', price: 2400, is_shipping: false},
    {id: 9, name: 'Online Superheroes Program (24 sessions)', price: 3750, is_shipping: false},
    {id: 10, name: 'Online Superheroes Program (48 sessions)', price: 6200, is_shipping: false},
    {id: 11, name: 'Online Rehabilitation Program (1 month)', price: 1500, is_shipping: false},
    {id: 12, name: 'Online Rehabilitation Program (3 months)', price: 3500, is_shipping: false},
    {id: 13, name: 'MyZone Belt', price: 2500, is_shipping: true},
    {id: 14, name: 'Online Classes (2 weeks)', price: 1000, is_shipping: false},
    {id: 15, name: 'Online Classes (1 month)', price: 1500, is_shipping: false},
]
